version: "3"

services:
  aihr-admin:
    image: rs_backend
    restart: unless-stopped
    ports:
      - 9587:9587
    networks:
      - infra
    environment:
      - APP_APP.PORT=1234
networks:
  infra:
    external: true
